image: docker:stable

services:
  - docker:dind

build-master:
    only: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: index.docker.io/polyswarm/transaction-signer
    stage: build
    script:
        - docker login -u "$CI_CUSTOM_DOCKER_HUB_USERNAME" -p "$CI_CUSTOM_DOCKER_HUB_PASSWORD" $CI_CUSTOM_DOCKER_HUB_URI
        - docker build -t $DOCKER_FULL_PATH .
        - docker push $DOCKER_FULL_PATH

build-non-master:
    except: 
        - master
    tags:
        - docker
    variables:
        DOCKER_FULL_PATH: "$CI_REGISTRY_IMAGE/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
    stage: build
    script:
        - docker build -t $DOCKER_FULL_PATH .
